// Auto generated - do not modify
// Copyright (c) 2014-2016 The Khronos Group Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and/or associated documentation files (the "Materials"),
// to deal in the Materials without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Materials, and to permit persons to whom the
// Materials are furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Materials.
// 
// MODIFICATIONS TO THIS FILE MAY MEAN IT NO LONGER ACCURATELY REFLECTS KHRONOS
// STANDARDS. THE UNMODIFIED, NORMATIVE VERSIONS OF KHRONOS SPECIFICATIONS AND
// HEADER INFORMATION ARE LOCATED AT https://www.khronos.org/registry/ 
// 
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM,OUT OF OR IN CONNECTION WITH THE MATERIALS OR THE USE OR OTHER DEALINGS
// IN THE MATERIALS.
#pragma once

namespace spvgentwo::opencl100
{
	static constexpr unsigned int Version = 100;
	static constexpr unsigned int Revision = 2;
	enum class Op : unsigned
	{
		acos = 0,
		acosh = 1,
		acospi = 2,
		asin = 3,
		asinh = 4,
		asinpi = 5,
		atan = 6,
		atan2 = 7,
		atanh = 8,
		atanpi = 9,
		atan2pi = 10,
		cbrt = 11,
		ceil = 12,
		copysign = 13,
		cos = 14,
		cosh = 15,
		cospi = 16,
		erfc = 17,
		erf = 18,
		exp = 19,
		exp2 = 20,
		exp10 = 21,
		expm1 = 22,
		fabs = 23,
		fdim = 24,
		floor = 25,
		fma = 26,
		fmax = 27,
		fmin = 28,
		fmod = 29,
		fract = 30,
		frexp = 31,
		hypot = 32,
		ilogb = 33,
		ldexp = 34,
		lgamma = 35,
		lgamma_r = 36,
		log = 37,
		log2 = 38,
		log10 = 39,
		log1p = 40,
		logb = 41,
		mad = 42,
		maxmag = 43,
		minmag = 44,
		modf = 45,
		nan = 46,
		nextafter = 47,
		pow = 48,
		pown = 49,
		powr = 50,
		remainder = 51,
		remquo = 52,
		rint = 53,
		rootn = 54,
		round = 55,
		rsqrt = 56,
		sin = 57,
		sincos = 58,
		sinh = 59,
		sinpi = 60,
		sqrt = 61,
		tan = 62,
		tanh = 63,
		tanpi = 64,
		tgamma = 65,
		trunc = 66,
		half_cos = 67,
		half_divide = 68,
		half_exp = 69,
		half_exp2 = 70,
		half_exp10 = 71,
		half_log = 72,
		half_log2 = 73,
		half_log10 = 74,
		half_powr = 75,
		half_recip = 76,
		half_rsqrt = 77,
		half_sin = 78,
		half_sqrt = 79,
		half_tan = 80,
		native_cos = 81,
		native_divide = 82,
		native_exp = 83,
		native_exp2 = 84,
		native_exp10 = 85,
		native_log = 86,
		native_log2 = 87,
		native_log10 = 88,
		native_powr = 89,
		native_recip = 90,
		native_rsqrt = 91,
		native_sin = 92,
		native_sqrt = 93,
		native_tan = 94,
		s_abs = 141,
		s_abs_diff = 142,
		s_add_sat = 143,
		u_add_sat = 144,
		s_hadd = 145,
		u_hadd = 146,
		s_rhadd = 147,
		u_rhadd = 148,
		s_clamp = 149,
		u_clamp = 150,
		clz = 151,
		ctz = 152,
		s_mad_hi = 153,
		u_mad_sat = 154,
		s_mad_sat = 155,
		s_max = 156,
		u_max = 157,
		s_min = 158,
		u_min = 159,
		s_mul_hi = 160,
		rotate = 161,
		s_sub_sat = 162,
		u_sub_sat = 163,
		u_upsample = 164,
		s_upsample = 165,
		popcount = 166,
		s_mad24 = 167,
		u_mad24 = 168,
		s_mul24 = 169,
		u_mul24 = 170,
		u_abs = 201,
		u_abs_diff = 202,
		u_mul_hi = 203,
		u_mad_hi = 204,
		fclamp = 95,
		degrees = 96,
		fmax_common = 97,
		fmin_common = 98,
		mix = 99,
		radians = 100,
		step = 101,
		smoothstep = 102,
		sign = 103,
		cross = 104,
		distance = 105,
		length = 106,
		normalize = 107,
		fast_distance = 108,
		fast_length = 109,
		fast_normalize = 110,
		bitselect = 186,
		select = 187,
		vloadn = 171,
		vstoren = 172,
		vload_half = 173,
		vload_halfn = 174,
		vstore_half = 175,
		vstore_half_r = 176,
		vstore_halfn = 177,
		vstore_halfn_r = 178,
		vloada_halfn = 179,
		vstorea_halfn = 180,
		vstorea_halfn_r = 181,
		shuffle = 182,
		shuffle2 = 183,
		printf = 184,
		prefetch = 185,
		Max = 0x7fffffff
	};
} // spvgentwo::opencl100
